"""OpenAPI 3.0.0 Compatibility and Swagger UI Configuration.

Ensures the OpenAPI schema generated by FastAPI / Pydantic v2 is 100% compliant
with OpenAPI 3.0.0 specification (replacing OpenAPI 3.1.0 JSON Schema 2020-12
constructs such as {"type": "null"} with "nullable: true", and multipart
file upload types with "format: binary").
"""

from __future__ import annotations

from typing import Any
from fastapi import FastAPI
from fastapi.openapi.utils import get_openapi
from fastapi.responses import HTMLResponse
from scalar_fastapi import Layout, SearchHotKey, Theme, get_scalar_api_reference


def downgrade_to_openapi_3_0(schema_dict: Any) -> Any:
    """Recursively downgrade schema constructs from OpenAPI 3.1 to OpenAPI 3.0.0.

    Transformations:
    1. anyOf with null -> nullable: true + unwrap single element
    2. contentMediaType: application/octet-stream -> type: string, format: binary
    3. const: value -> enum: [value]
    4. prefixItems -> items
    """
    if isinstance(schema_dict, dict):
        # 1. Handle anyOf containing {"type": "null"}
        if "anyOf" in schema_dict and isinstance(schema_dict["anyOf"], list):
            non_null = [
                item
                for item in schema_dict["anyOf"]
                if not (isinstance(item, dict) and item.get("type") == "null")
            ]
            has_null = len(non_null) < len(schema_dict["anyOf"])
            if has_null:
                schema_dict["nullable"] = True
                if len(non_null) == 1:
                    target = non_null[0]
                    del schema_dict["anyOf"]
                    if isinstance(target, dict):
                        for k, v in target.items():
                            if k not in schema_dict:
                                schema_dict[k] = v
                else:
                    schema_dict["anyOf"] = non_null

        # 2. Handle file upload (OpenAPI 3.1 contentMediaType -> OpenAPI 3.0 format: binary)
        if schema_dict.get("contentMediaType") == "application/octet-stream":
            schema_dict.pop("contentMediaType", None)
            schema_dict["type"] = "string"
            schema_dict["format"] = "binary"

        # 3. Handle const (OpenAPI 3.1 / JSON Schema draft 2020-12)
        if "const" in schema_dict:
            const_val = schema_dict.pop("const")
            schema_dict["enum"] = [const_val]

        # 4. Handle prefixItems (tuples in OpenAPI 3.1)
        if "prefixItems" in schema_dict and "items" not in schema_dict:
            prefix = schema_dict.pop("prefixItems")
            if prefix and isinstance(prefix, list):
                schema_dict["items"] = prefix[0]

        # Recursively process children
        for key, value in list(schema_dict.items()):
            schema_dict[key] = downgrade_to_openapi_3_0(value)

    elif isinstance(schema_dict, list):
        for i, item in enumerate(schema_dict):
            schema_dict[i] = downgrade_to_openapi_3_0(item)

    return schema_dict


def get_scalar_html(
    *,
    openapi_url: str = "/openapi.json",
    title: str = "Scalar API Reference",
    theme: str | Theme = Theme.DEFAULT,
    dark_mode: bool = True,
    layout: str | Layout = Layout.MODERN,
    show_sidebar: bool = True,
    search_hotkey: str | SearchHotKey = SearchHotKey.K,
    persist_auth: bool = True,
) -> HTMLResponse:
    """Generate modern Scalar API documentation HTML page (with dark mode, persistent auth, and search)."""
    return get_scalar_api_reference(
        openapi_url=openapi_url,
        title=title,
        theme=theme,
        dark_mode=dark_mode,
        layout=layout,
        show_sidebar=show_sidebar,
        search_hot_key=search_hotkey,
        persist_auth=persist_auth,
    )


def setup_openapi_3_0(app: FastAPI) -> None:
    """Configure FastAPI app to produce strict OpenAPI 3.0.0 documentation and mount Scalar UI."""
    app.openapi_version = "3.0.0"

    def custom_openapi() -> dict[str, Any]:
        if app.openapi_schema:
            return app.openapi_schema

        schema = get_openapi(
            title=app.title,
            version=app.version,
            openapi_version="3.0.0",
            summary=app.summary,
            description=app.description,
            terms_of_service=app.terms_of_service,
            contact=app.contact,
            license_info=app.license_info,
            routes=app.routes,
            webhooks=app.webhooks.routes if hasattr(app, "webhooks") and app.webhooks else None,
            tags=app.openapi_tags,
            servers=app.servers,
            separate_input_output_schemas=app.separate_input_output_schemas,
            external_docs=app.openapi_external_docs,
        )

        # Force OpenAPI 3.0.0 specification header
        schema["openapi"] = "3.0.0"

        # Register security schemes (Session Cookie & Bearer Token)
        components = schema.setdefault("components", {})
        security_schemes = components.setdefault("securitySchemes", {})
        security_schemes["cookieAuth"] = {
            "type": "apiKey",
            "in": "cookie",
            "name": "session_token",
            "description": "Session token stored in HTTP-only cookie",
        }
        security_schemes["session"] = {
            "type": "apiKey",
            "in": "cookie",
            "name": "session_token",
            "description": "Session token cookie matching ViShop's @ApiCookieAuth('session')",
        }
        security_schemes["bearerAuth"] = {
            "type": "http",
            "scheme": "bearer",
            "description": "Session token passed in Authorization: Bearer <token>",
        }

        # Downgrade schema definitions to strict 3.0.0
        downgrade_to_openapi_3_0(schema)

        app.openapi_schema = schema
        return app.openapi_schema

    app.openapi = custom_openapi

    # Mount modern Scalar API Reference at /api/docs, /docs, and /scalar

    @app.get("/docs", include_in_schema=False)

    async def scalar_docs() -> HTMLResponse:
        return get_scalar_html(
            openapi_url=app.openapi_url or "/openapi.json",
            title=f"{app.title} - API Reference",
        )

