"""Shared authentication and authorization primitives, guards, and catalogs."""

from __future__ import annotations

from chat_api.shared.auth.guards import (
    AuthContext,
    AuthDep,
    CurrentAuth,
    CurrentPrincipalDep,
    RequireAnyPermission,
    RequireAuth,
    RequireAuthDep,
    RequirePermission,
    RequireRole,
    api_cookie_auth,
    api_workspace_header,
    auth_openapi,
    bearer_scheme,
    extract_session_token,
    get_auth_context,
    get_current_principal,
    require_auth,
    resolve_target_workspace_id,
)
from chat_api.shared.auth.permissions import (
    ALL_PERMISSION_CODES,
    BUILTIN_ROLE_PERMISSIONS,
    PERMISSION_CATALOG,
    ROLE_PERMISSIONS,
    CurrentPrincipal,
    ExecutionContext,
    Permission,
    PermissionItem,
    effective_permissions,
    get_permissions_for_role,
    require_document_access,
    require_session_access,
    require_workspace_member,
    require_workspace_permission,
)

__all__ = [
    # Guards & Dependencies
    "AuthContext",
    "CurrentAuth",
    "AuthDep",
    "CurrentPrincipalDep",
    "RequireAuth",
    "RequireAuthDep",
    "require_auth",
    "RequireAnyPermission",
    "RequirePermission",
    "RequireRole",
    "api_cookie_auth",
    "api_workspace_header",
    "auth_openapi",
    "bearer_scheme",
    "extract_session_token",
    "get_auth_context",
    "get_current_principal",
    "resolve_target_workspace_id",
    # Permissions & Catalog
    "Permission",
    "PermissionItem",
    "PERMISSION_CATALOG",
    "ALL_PERMISSION_CODES",
    "BUILTIN_ROLE_PERMISSIONS",
    "ROLE_PERMISSIONS",
    "get_permissions_for_role",
    "effective_permissions",
    "CurrentPrincipal",
    "ExecutionContext",
    "require_workspace_member",
    "require_document_access",
    "require_session_access",
    "require_workspace_permission",
]
