"""describe change

Revision ID: cfc53009db86
Revises: 20260728_0001
Create Date: 2026-07-28 16:19:40.490905
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cfc53009db86'
down_revision: Union[str, Sequence[str], None] = '20260728_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_fts_simple'), table_name='document_chunks', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_chunks_fts_simple'), 'document_chunks', [sa.literal_column("to_tsvector('simple'::regconfig, content)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
